# _______| |__  
#|_  / __| '_ \ 
# / /\__ \ | | |
#/___|___/_| |_|
#               

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

export TERM=xterm-256color
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export TERM_ITALICS=true
export RANGER_LOAD_DEFAULT_RC="false"
export TERM=screen-256color
export EDITOR=nvim

export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

alias c='clear'
alias cdiff='colordiff'
alias cs='cowsay'
alias dv='deactivate'
alias gc='git config credential.helper store'
alias ipy='ipython'
alias l='ls -la'
alias lg='lazygit'
alias ms='mailsync'
alias mt='neomutt'
alias r='echo $RANGER_LEVEL'
alias pu='python3 -m pudb'
alias ra='ranger'
# ra() {
	#if [ -z "$RANGER_LEVEL" ]
	#then
		#ranger
	#else
		#exit
	#fi
#}
alias s='neofetch'
alias g='onefetch'
alias sra='sudo -E ranger'
alias sudo='sudo -E'
alias vim='nvim'
alias gs='git config credential.helper store'
alias bat='sudo tlp bat'
alias ac='sudo tlp ac'
alias gy='git-yolo'

alias hp="hexo clean && hexo g && hexo d"
alias gacp="git add . && git ci -m 'update' && git push"
alias proxy='export http_proxy=socks5://127.0.0.1:1080'
alias cip='curl cip.cc'

bindkey -v
bindkey -M vicmd "k" vi-insert
bindkey -M vicmd "K" vi-insert-bol
bindkey -M vicmd "n" vi-backward-char
bindkey -M vicmd "i" vi-forward-char
bindkey -M vicmd "N" vi-beginning-of-line
bindkey -M vicmd "I" vi-end-of-line
bindkey -M vicmd "e" down-line-or-history
bindkey -M vicmd "u" up-line-or-history
bindkey -M vicmd "l" undo
#bindkey -M vicmd "-" vi-rev-repeat-search
bindkey -M vicmd "=" vi-repeat-search
bindkey -M vicmd "h" vi-forward-word-end

#function zle-line-init zle-keymap-select {
	#RPS1="${${KEYMAP/vicmd/-- NOR --}/(main|viins)/-- INS --}"
	#RPS2=$RPS1
	#zle reset-prompt
#}

function zle-keymap-select {
	if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
		echo -ne '\e[1 q'
	elif [[ ${KEYMAP} == main ]] || [[ ${KEYMAP} == viins ]] || [[ ${KEYMAP} = '' ]] || [[ $1 = 'beam' ]]; then
		echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select

# Use beam shape cursor on startup.
echo -ne '\e[5 q'

# Use beam shape cursor for each new prompt.
preexec() {
	echo -ne '\e[5 q'
}

_fix_cursor() {
	echo -ne '\e[5 q'
}
precmd_functions+=(_fix_cursor)


zle -N zle-line-init
zle -N zle-keymap-select

KEYTIMEOUT=1

ZSH_THEME="robbyrussell"

# plugs
plugins=(
	git 
	vi-mode 
	z 
	extract
	zsh-syntax-highlighting
	zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

alias ohmyzsh="mate ~/.oh-my-zsh"

export M2_HOME=~/developer_tool/apache-maven-3.6.3
export PATH=$PATH:$M2_HOME/bin

# add time
HIST_STAMPS="yyyy-mm-dd"

# fzf
export FZF_DEFAULT_OPTS='--bind ctrl-e:down,ctrl-u:up --preview "[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500"'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_COMPLETION_TRIGGER='\'
export FZF_TMUX_HEIGHT='80%'
export FZF_PREVIEW_COMMAND='[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'
source ~/.config/zsh/key-bindings.zsh
source ~/.config/zsh/completion.zsh

# terminal start
function start(){
	start_say=("wish you no bug" "佛祖保佑，永无Bug")
	start_random=$[$RANDOM%2]
	cowsay $start_say[$start_random]
}
start



